import { Campaign, Context } from './types';

export const INITIAL_CONTEXT: Context = {
    company_stage: 'Scale',
    strategic_priority: 'Growth',
    finance_capacity: 'Medium',
    base_roi_threshold: 2.0,
    risk_tolerance: 'Medium',
};

export const MOCK_CAMPAIGNS: Campaign[] = [
    {
        campaign_id: 'C001',
        campaign_name: 'Global ITSM Webinar Series',
        quarter: '2025Q4',
        region: 'EMEA',
        channel: 'Webinar',
        product_line: 'ITSM',
        cost_eur: 45000,
        leads: 1200,
        mqls: 450,
        sqls: 120,
        opps_created: 45,
        deals_won: 12,
        avg_acv_eur: 85000,
        win_rate: 0.26,
        sales_cycle_days: 95,
        retention_uplift_pp: 1.5,
        notes: 'Strong engagement from DACH region.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C002',
        campaign_name: 'NA SecOps Paid Search',
        quarter: '2025Q4',
        region: 'NA',
        channel: 'Paid Search',
        product_line: 'SecOps',
        cost_eur: 120000,
        leads: 3500,
        mqls: 800,
        sqls: 200,
        opps_created: 85,
        deals_won: 18,
        avg_acv_eur: 110000,
        win_rate: 0.21,
        sales_cycle_days: 110,
        retention_uplift_pp: 0.5,
        notes: 'High CPL but strong ACV.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C003',
        campaign_name: 'APAC CSM Partner Day',
        quarter: '2026Q1',
        region: 'APAC',
        channel: 'Partner',
        product_line: 'CSM',
        cost_eur: 65000,
        leads: 450,
        mqls: 150,
        sqls: 60,
        opps_created: 30,
        deals_won: 9,
        avg_acv_eur: 75000,
        win_rate: 0.3,
        sales_cycle_days: 135,
        retention_uplift_pp: 2.1,
        notes: 'Partner lead quality is high.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C004',
        campaign_name: 'LinkedIn ABM - Financial Services',
        quarter: '2025Q4',
        region: 'NA',
        channel: 'LinkedIn',
        product_line: 'ITSM',
        cost_eur: 30000,
        leads: 200,
        mqls: 85,
        sqls: 40,
        opps_created: 15,
        deals_won: 4,
        avg_acv_eur: 150000,
        win_rate: 0.27,
        sales_cycle_days: 75,
        retention_uplift_pp: 0,
        notes: 'Lacks retention data.',
        data_quality_score: 0.85,
        issues: ['Missing retention_uplift_pp'],
    },
    {
        campaign_id: 'C005',
        campaign_name: 'EMEA CSM Roadshow',
        quarter: '2026Q1',
        region: 'EMEA',
        channel: 'Event',
        product_line: 'CSM',
        cost_eur: 85000,
        leads: 600,
        mqls: 200,
        sqls: 90,
        opps_created: 40,
        deals_won: 10,
        avg_acv_eur: 60000,
        win_rate: 0.25,
        sales_cycle_days: 150,
        retention_uplift_pp: 3.5,
        notes: 'Excellent for retention but long cycle.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C006',
        campaign_name: 'SecOps Threat Report Webinar',
        quarter: '2025Q4',
        region: 'EMEA',
        channel: 'Webinar',
        product_line: 'SecOps',
        cost_eur: 15000,
        leads: 2500,
        mqls: 900,
        sqls: 150,
        opps_created: 35,
        deals_won: 7,
        avg_acv_eur: 45000,
        win_rate: 0.2, // Low win rate
        sales_cycle_days: 60,
        retention_uplift_pp: 0.2,
        notes: 'High volume, low efficiency.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C007',
        campaign_name: 'NA ITSM Search Expansion',
        quarter: '2026Q1',
        region: 'NA',
        channel: 'Paid Search',
        product_line: 'ITSM',
        cost_eur: 250000, // Very high cost
        leads: 8000,
        mqls: 2000,
        sqls: 450,
        opps_created: 120,
        deals_won: 22,
        avg_acv_eur: 95000,
        win_rate: 0.18,
        sales_cycle_days: 100,
        retention_uplift_pp: -0.5,
        notes: 'Scaling too fast? Cost is extreme.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C008',
        campaign_name: 'APAC SecOps Partner Summit',
        quarter: '2026Q1',
        region: 'APAC',
        channel: 'Partner',
        product_line: 'SecOps',
        cost_eur: 55000,
        leads: 300,
        mqls: 120,
        sqls: 45,
        opps_created: 25,
        deals_won: 10,
        avg_acv_eur: 130000,
        win_rate: 0.4,
        sales_cycle_days: 110,
        retention_uplift_pp: 1.2,
        notes: 'Premium partner segment.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C009',
        campaign_name: 'EMEA LinkedIn SecOps Campaign',
        quarter: '2025Q4',
        region: 'EMEA',
        channel: 'LinkedIn',
        product_line: 'SecOps',
        cost_eur: 40000,
        leads: 350,
        mqls: 110,
        sqls: 35,
        opps_created: 12,
        deals_won: 3,
        avg_acv_eur: 115000,
        win_rate: 0.25,
        sales_cycle_days: 85,
        retention_uplift_pp: 0.8,
        notes: 'Targeting CTOs.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C010',
        campaign_name: 'NA CSM Webinar - Customer Success',
        quarter: '2026Q1',
        region: 'NA',
        channel: 'Webinar',
        product_line: 'CSM',
        cost_eur: 20000,
        leads: 1500,
        mqls: 550,
        sqls: 130,
        opps_created: 40,
        deals_won: 12,
        avg_acv_eur: 55000,
        win_rate: 0.3,
        sales_cycle_days: 70,
        retention_uplift_pp: 4.2,
        notes: 'High retention focus.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C011',
        campaign_name: 'APAC ITSM Roadshow',
        quarter: '2025Q4',
        region: 'APAC',
        channel: 'Event',
        product_line: 'ITSM',
        cost_eur: 75000,
        leads: 400,
        mqls: 140,
        sqls: 55,
        opps_created: 25,
        deals_won: 6,
        avg_acv_eur: 90000,
        win_rate: 0.24,
        sales_cycle_days: 140,
        retention_uplift_pp: 0.4,
        notes: 'Slower deal closure in region.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C012',
        campaign_name: 'EMEA Paid Search - CSM',
        quarter: '2026Q1',
        region: 'EMEA',
        channel: 'Paid Search',
        product_line: 'CSM',
        cost_eur: 50000,
        leads: 1800,
        mqls: 600,
        sqls: 140,
        opps_created: 45,
        deals_won: 15,
        avg_acv_eur: 45000,
        win_rate: 0.33,
        sales_cycle_days: 80,
        retention_uplift_pp: 1.1,
        notes: 'Steady performance.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C013',
        campaign_name: 'Global SecOps Partner Portal',
        quarter: '2025Q4',
        region: 'EMEA', // Mix regions?
        channel: 'Partner',
        product_line: 'SecOps',
        cost_eur: 25000,
        leads: 300,
        mqls: 100,
        sqls: 40,
        opps_created: 18,
        deals_won: 5,
        avg_acv_eur: 120000,
        win_rate: 0.28,
        sales_cycle_days: 90,
        retention_uplift_pp: 0.3,
        notes: 'Cost effecient.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C014',
        campaign_name: 'NA LinkedIn SecOps Lead Gen',
        quarter: '2026Q1',
        region: 'NA',
        channel: 'LinkedIn',
        product_line: 'SecOps',
        cost_eur: 55000,
        leads: 400,
        mqls: 160,
        sqls: 50,
        opps_created: 20,
        deals_won: 6,
        avg_acv_eur: 110000,
        win_rate: 0.3,
        sales_cycle_days: 95,
        retention_uplift_pp: 0.2,
        notes: 'Competitive landscape.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C015',
        campaign_name: 'APAC Webinar - ITSM Best Practices',
        quarter: '2025Q4',
        region: 'APAC',
        channel: 'Webinar',
        product_line: 'ITSM',
        cost_eur: 12000,
        leads: 900,
        mqls: 300,
        sqls: 80,
        opps_created: 25,
        deals_won: 8,
        avg_acv_eur: 65000,
        win_rate: 0.32,
        sales_cycle_days: 85,
        retention_uplift_pp: 0.9,
        notes: 'High conversion.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C016',
        campaign_name: 'EMEA Partner Co-Marketing',
        quarter: '2026Q1',
        region: 'EMEA',
        channel: 'Partner',
        product_line: 'ITSM',
        cost_eur: 90000,
        leads: 1100,
        mqls: 400,
        sqls: 110,
        opps_created: 50,
        deals_won: 15,
        avg_acv_eur: 95000,
        win_rate: 0.3,
        sales_cycle_days: 120,
        retention_uplift_pp: 1.8,
        notes: 'Strategic alliance.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C017',
        campaign_name: 'NA Event - IT Expo 2026',
        quarter: '2026Q1',
        region: 'NA',
        channel: 'Event',
        product_line: 'ITSM',
        cost_eur: 150000,
        leads: 2500,
        mqls: 900,
        sqls: 250,
        opps_created: 80,
        deals_won: 20,
        avg_acv_eur: 100000,
        win_rate: 0.25,
        sales_cycle_days: 150,
        retention_uplift_pp: 0.1,
        notes: 'Large brand presence.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C018',
        campaign_name: 'APAC CSM Paid Search',
        quarter: '2025Q4',
        region: 'APAC',
        channel: 'Paid Search',
        product_line: 'CSM',
        cost_eur: 45000,
        leads: 1200,
        mqls: 400,
        sqls: 90,
        opps_created: 35,
        deals_won: 12,
        avg_acv_eur: 50000,
        win_rate: 0.34,
        sales_cycle_days: 85,
        retention_uplift_pp: 0.6,
        notes: 'Good efficiency.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C019',
        campaign_name: 'EMEA SecOps Event - Paris',
        quarter: '2026Q1',
        region: 'EMEA',
        channel: 'Event',
        product_line: 'SecOps',
        cost_eur: 110000,
        leads: 800,
        mqls: 300,
        sqls: 80,
        opps_created: 40,
        deals_won: 10,
        avg_acv_eur: 110000,
        win_rate: 0.25,
        sales_cycle_days: 130,
        retention_uplift_pp: 0.5,
        notes: 'High cost per lead.',
        data_quality_score: 1.0,
        issues: [],
    },
    {
        campaign_id: 'C020',
        campaign_name: 'Problematic APAC SecOps Campaign',
        quarter: '2025Q4',
        region: 'APAC',
        channel: 'LinkedIn',
        product_line: 'SecOps',
        cost_eur: 20000,
        leads: 100,
        mqls: 30,
        sqls: 10,
        opps_created: 5,
        deals_won: 1,
        avg_acv_eur: 0, // Missing ACV
        win_rate: 0.2,
        sales_cycle_days: 200, // Very long
        retention_uplift_pp: -2.5, // Negative retention
        notes: 'Data issues and poor performance.',
        data_quality_score: 0.5,
        issues: ['Missing avg_acv_eur', 'Long cycle time', 'Negative retention uplift'],
    },
];
